"""Shared builders and the hypothesis profile.

Nothing here reads a clock, a file or the network — the package cannot, and neither can its tests.
"""

from __future__ import annotations

from hypothesis import HealthCheck, settings

from cutctx import (
    CompactionBudget,
    CompactionPlan,
    Role,
    Transcript,
    TranscriptTurn,
)

settings.register_profile(
    "cutctx",
    max_examples=150,
    # `pytest-randomly` reseeds every test, so a property failure is not reproducible from the
    # command line alone. `print_blob` makes each failure carry its own replay: hypothesis prints
    # an `@reproduce_failure(...)` decorator to paste onto the test. The seed pytest-randomly
    # prints at the top of a run reproduces the *ordering*; the blob reproduces the *example*.
    print_blob=True,
    # Property tests here run under coverage and under `pytest-randomly`'s reordering; a per-example
    # deadline would turn a slow machine into a flaky suite, and none of these properties is about
    # speed. Speed is asserted separately, under the `performance` marker (spec §15).
    deadline=None,
    # Transcripts are generated by construction rather than by filtering (see
    # `tests/property/strategies.py`), so `filter_too_much` should never fire; if it ever does, it
    # is a real regression in the generators and should be seen rather than suppressed.
    suppress_health_check=(HealthCheck.too_slow,),
)
settings.load_profile("cutctx")


def turn(
    turn_id: str,
    role: Role = Role.USER,
    *,
    tokens: int = 10,
    content: str | None = None,
    tool_call_id: str | None = None,
    pinned: bool = False,
) -> TranscriptTurn:
    """Build one turn with everything but its id defaulted."""
    return TranscriptTurn(
        turn_id=turn_id,
        role=role,
        content=content if content is not None else f"content of {turn_id}",
        token_estimate=tokens,
        tool_call_id=tool_call_id,
        pinned=pinned,
    )


def transcript(*turns: TranscriptTurn) -> Transcript:
    """Build a transcript from turns given positionally."""
    return Transcript(turns=turns)


def rebuilt(
    plan: CompactionPlan,
    transcript: Transcript,
    budget: CompactionBudget,
    **overrides: object,
) -> CompactionPlan:
    """Reconstruct ``plan`` with fields overridden — the only way to attempt an invalid plan.

    ``dataclasses.replace`` cannot do this: the transcript and budget are ``InitVar``s, so they
    are not fields to copy forward. That is the guard working, and this helper is what a test uses
    to write the plan a delinquent policy would have written.
    """
    fields: dict[str, object] = {
        "actions": plan.actions,
        "summarization_requests": plan.summarization_requests,
        "tokens_before": plan.tokens_before,
        "tokens_after_estimate": plan.tokens_after_estimate,
        "policy_name": plan.policy_name,
        "policy_version": plan.policy_version,
        "estimator_ratio": plan.estimator_ratio,
        "budget_unmet": plan.budget_unmet,
    }
    fields.update(overrides)
    return CompactionPlan(**fields, transcript=transcript, budget=budget)  # type: ignore[arg-type]  # a deliberate override of typed fields
